version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://appuser:apppass@db:5432/appdb
      JWT_SECRET: "replace-this-in-prod"
      FILES_DIR: "/app/files"
      CORS_ORIGINS: "http://localhost:5173"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/files:/app/files
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  dbdata:
